### ISSUE TITLE
last url in csv is always detected as failed url

### ISSUE THREAD

**Issue by arjunraghunandanan** [dsc-vast/30-Days-GCloud-Dashboard#15]
whan the script runs , the file at
30-Days-GCloud-Dashboard-main\scrapper\user.txt
will be fetched into the program, but the last character in the last url is not fetched and it will return "failed url" even though the url in csv is valid
example
expected url : https://www.qwiklabs.com/public_profiles/2648e85b-eed1-444f-a21a-864da942d851
fetched url    : https://www.qwiklabs.com/public_profiles/2648e85b-eed1-444f-a21a-864da942d85

**Comment by jijinharidas** [comment]
#16 solves this issue.
